accounts/urls.py
from django.urls import path
from .views import login_view, register, custom_logout, profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', custom_logout, name='logout'),
    path('profile/', profile, name='profile'),
]

cart/urls.py
from django.urls import path
from . import views, api_views
app_name = 'cart'

urlpatterns = [
    path('api/cart/', api_views.get_cart_api, name='get_cart_api'),
    path('api/cart/add/<int:dish_id>/', api_views.add_to_cart_api, name='add_to_cart_api'),
    path('api/cart/remove/<int:dish_id>/', api_views.remove_from_cart_api, name='remove_from_cart_api'),
    
    
    # path('add_to_cart/<int:dish_id>/', views.add_to_cart, name='add_to_cart'),
    # path('remove_from_cart/<int:dish_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order/', views.cart_page, name='cart-page'),

]

menu/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='home'),
    path('test/', views.test, name='test-page'),
    path('api/products/<int:product_id>/', views.get_product_data, name='get_product_data'),
    ]

restaurantapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.models import CustomUser


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название категории")
    icon_class = models.CharField(max_length=100, default="123", verbose_name="Класс иконки font-awesome")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/Category/{self.id}'

class Dishes(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    description = models.TextField(blank=True, verbose_name="Описание")
    photolink = models.CharField(max_length=255, verbose_name="Фотография")
    rate = models.DecimalField(max_digits=2, decimal_places=1, validators=[MinValueValidator(0), MaxValueValidator(5)],  verbose_name="Рейтинг")
    grams = models.CharField(max_length=50, verbose_name="Граммы")
    kalories = models.DecimalField(max_digits=6, decimal_places=1, verbose_name="Калории")
    protein = models.DecimalField(max_digits=3, decimal_places=1, verbose_name="Белки")
    fat = models.DecimalField(max_digits=3, decimal_places=1, verbose_name="Жиры")
    carbohydrates = models.DecimalField(max_digits=3, decimal_places=1, verbose_name="Углеводы")
    structure = models.CharField(max_length=255, verbose_name="Состав")
    is_available = models.BooleanField(default=False, verbose_name="Доступен для заказа")
    is_new = models.BooleanField(default=False, verbose_name="Новое")
    is_hit = models.BooleanField(default=False, verbose_name="Хит")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория", related_name="products")

    def __str__(self):
        return self.name

menu/views.py
from django.shortcuts import render
from .models import Category, Dishes
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from cart.models import Cart, CartItem
from orders.models import Order

def index(request):
    categories = Category.objects.prefetch_related('products').all()
    all_products = Dishes.objects.prefetch_related('category').all()
    novelty_products = Dishes.objects.filter(is_new=True)
    hit_products = Dishes.objects.filter(is_hit=True)

    if request.user.is_authenticated:
        cart = Cart.objects.filter(user=request.user).first()
    else:
        cart = Cart.objects.filter(session_key=request.session.session_key).first()
    cart_items = CartItem.objects.filter(cart=cart)
    total_price = sum(item.dishes.price * item.quantity for item in cart_items)

    cart_items = CartItem.objects.filter(cart=cart)
    total_price = sum(item.dishes.price * item.quantity for item in cart_items)

    active_order = None
    if request.user.is_authenticated:
        active_order = Order.objects.filter(user=request.user, status='Готовится').first()

    return render(request, 'menu/index.html', {
        'active_order': active_order,
        'categories': categories,
        'all_products': all_products,
        'novelty_products': novelty_products,
        'hit_products': hit_products,
        'cart_items': cart_items,
        'total_price': total_price,
    })

def test(request):
    categories = Category.objects.prefetch_related('products').all()
    all_products = Dishes.objects.prefetch_related('category').all()
    novelty_products = Dishes.objects.filter(is_new=True)
    hit_products = Dishes.objects.filter(is_hit=True)
    return render(request, 'menu/test.html', {
        'categories': categories,
        'all_products': all_products,
        'novelty_products': novelty_products,
        'hit_products': hit_products,
    })

def get_product_data(request, product_id):
    product = get_object_or_404(Dishes, id=product_id)
    data = {
        'name': product.name,
        'photolink': product.photolink,
        'description': product.description,
        'price': product.price,
        'grams': str(product.grams),
        'structure': product.structure,
        'kalories': str(product.kalories),
        'protein': str(product.protein),
        'fat': str(product.fat),
        'carbohydrates': str(product.carbohydrates),
        'category': product.category.name,
    }

    return JsonResponse(data)

menu/templates/menu/dish_card.html
{% load static %}

<div class="menu-card">
    <div class="card-content" 
         data-bs-toggle="modal-product"
         data-product-id="{{ product.id }}">
        <div class="menu-img">
            <img src="{% static 'menu/img/' %}{{ product.photolink }}.jpg" alt="{{ product.name }}">
            <div class="img-overlay">
                <i class="fa-solid fa-magnifying-glass-plus"></i>
            </div>
        </div>
        <div class="menu-body">
            <h5 class="menu-title">{{ product.name }}</h5>
            <div class="menu-details">
                <span class="menu-weight">
                    <i class="fa-solid fa-weight-hanging me-1"></i>{{ product.grams }}г
                </span>
                <span class="menu-price">
                    <i class="fa-solid fa-ruble-sign me-1"></i>{{ product.price }}
                </span>
            </div>
        </div>
    </div>
    <button class="btn btn-add" 
            data-bs-toggle="addToCart"
            data-dish-id="{{ product.id }}">
        <i class="fa-solid fa-cart-plus me-2"></i>Добавить
    </button>
</div>

menu/templates/menu/footer.html
<div class="container">
    <footer class="py-4 mt-4">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item">
                        <a href="#" class="nav-link px-3 text-primary">
                            <i class="fa-solid fa-house me-2"></i>Главная
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link px-3 text-primary">
                            <i class="fa-solid fa-utensils me-2"></i>Меню
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link px-3 text-primary">
                            <i class="fa-solid fa-phone me-2"></i>Контакты
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link px-3 text-primary">
                            <i class="fa-solid fa-circle-info me-2"></i>О нас
                        </a>
                    </li>
                </ul>
                <div class="d-flex justify-content-center mb-3">
                    <a href="#" class="text-primary me-3">
                        <i class="fab fa-vk fa-lg"></i>
                    </a>
                    <a href="#" class="text-primary me-3">
                        <i class="fab fa-telegram fa-lg"></i>
                    </a>
                    <a href="#" class="text-primary">
                        <i class="fab fa-instagram fa-lg"></i>
                    </a>
                </div>
                <p class="text-center text-muted mb-0">
                    <i class="fa-regular fa-copyright me-2"></i>2024 Ресторан, Все права защищены
                </p>
            </div>
        </div>
    </footer>
</div>

<style>
    
</style>

menu/templates/menu/header.html
{% load static %}
<header class="p-3 mb-3 border-bottom position-sticky top-0 z-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'home' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none">
                <img src="{% static 'menu/img/Логотип2.png' %}" width="40" height="32" class="me-2" alt="">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li>
                    <a href="{% url 'home' %}" class="px-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Главная">
                        <i class="fa-solid fa-house menu-icon"></i>
                    </a>
                </li>
                <li>
                    <a href="{% url 'cart:cart-page' %}" class="px-2 " data-bs-toggle="tooltip" data-bs-placement="bottom" title="Корзина">
                        <i class="fa-solid fa-cart-shopping menu-icon"></i>
                        <span id="cart-badge" class="badge bg-danger"></span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'accounts:profile' %}" class="px-2">
                            <i class="fa-solid fa-user menu-icon"></i>
                        </a>
                    </li>
                {% endif %}
                {% comment %} <li>
                    <a href="{% url 'test-page' %}" class="px-2 " data-bs-toggle="tooltip" data-bs-placement="bottom" title="Настройки">
                        <i class="fa-solid fa-gear menu-icon"></i>
                    </a>
                </li> {% endcomment %}
            </ul>

            <div class="text-end">
                {% if request.user.is_authenticated %}
                    <div class="d-flex align-items-center">
                        <a href="{% url 'accounts:logout' %}" class="btn btn-outline-light">
                            <i class="fa-solid fa-right-from-bracket me-2"></i>Выйти
                        </a>
                    </div>
                {% else %}
                    <a href="#" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#loginModal">
                        <i class="fa-solid fa-right-to-bracket me-2"></i>Войти
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

menu/templates/menu/index.html
{% extends 'menu/layout.html' %}
{% load static %}

{% block title %}Меню ресторана{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        
        <!-- Sidebar с категориями -->
        {% include 'menu/sidebar.html' %}

        <main class="col-md-9 col-lg-6 mx-3">

        
            <!-- Hero секция -->
<div class="hero-section mb-5">
    <div class="hero-content text-center">
    
    
<!-- Hero секция с слайдером -->
<div id="heroCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <!-- Слайд для авторизованных пользователей -->
        {% if request.user.is_authenticated %}
        <div class="carousel-item active">
            <div class="hero-content text-center">
                {% if active_order %}
                    <h1 class="hero-title">Ваш заказ принят!</h1>
                    <p class="hero-subtitle">Номер заказа: #{{ active_order.id }}</p>
                    <p class="hero-subtitle">Комментарий: {{ active_order.comment|default:"Без комментария" }}</p>
                {% elif request.user.first_name %}
                    <h1 class="hero-title">С возвращением, {{ request.user.first_name }}!</h1>
                    <p class="hero-subtitle">Что бы вы хотели заказать сегодня?</p>
                {% else %}
                    <h1 class="hero-title">С возвращением, {{ request.user.username }}!</h1>
                    <p class="hero-subtitle">Что бы вы хотели заказать сегодня?</p>
                {% endif %}
            </div>
        </div>

        <div class="carousel-item">
            <div class="hero-content text-center">
                <h1 class="hero-title">Добро пожаловать в наш ресторан</h1>
                <p class="hero-subtitle">Попробуйте наши лучшие блюда</p>
            </div>
        </div>
        <!-- Слайд для неавторизованных пользователей -->
        {% else %}
        <div class="carousel-item active">
            <div class="hero-content text-center">
                <h1 class="hero-title">Добро пожаловать в наш ресторан</h1>
                <p class="hero-subtitle">Попробуйте наши лучшие блюда</p>
            </div>
        </div>

        <div class="carousel-item">
            <div class="hero-content text-center noselect">
                <h1 class="hero-title cursor-pointer" data-bs-toggle="modal" data-bs-target="#loginModal">Войти</h1>
                <p class="hero-subtitle">Для доступа к дополнительным функциям</p>
            </div>
        </div>
        {% endif %}
    </div>

    <!-- Кнопки управления слайдером -->
    <button class="carousel-control-prev" type="button" data-bs-target="#heroCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Предыдущий</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#heroCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Следующий</span>
    </button>
</div>

</div>
</div>

            <!-- Раздел новинок -->
            <section id="novelty" class="category-section mb-5">
                <div class="section-header">
                    <h2 class="section-title">
                        <i class="fas fa-star me-3"></i>Новинки
                        <span class="badge bg-primary ms-3">New</span>
                    </h2>
                </div>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 row-cols-xxxl-4 row-cols-xxxxl-5 g-4">
                    {% for product in novelty_products %}
                        <div class="col">
                            {% include 'menu/dish_card.html' %}
                        </div>
                    {% empty %}
                        <div class="col-12">
                            <div class="alert alert-info d-flex align-items-center">
                                <i class="fa-solid fa-info-circle me-2"></i>
                                <span>Новинок пока нет</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>

            <!-- Раздел хитов -->
            <section id="hits" class="category-section mb-5">
                <div class="section-header">
                    <h2 class="section-title">
                        <i class="fas fa-fire me-3"></i>Хиты продаж
                        <span class="badge bg-danger ms-3">Hot</span>
                    </h2>
                </div>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 row-cols-xxxl-4 row-cols-xxxxl-5 g-4">
                    {% for product in hit_products %}
                        <div class="col">
                            {% include 'menu/dish_card.html' %}
                        </div>
                    {% empty %}
                        <div class="col-12">
                            <div class="alert alert-info d-flex align-items-center">
                                <i class="fa-solid fa-info-circle me-2"></i>
                                <span>Хитов пока нет</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>

            <!-- Категории -->
            {% for category in categories %}
                    {% include 'menu/positions.html' %}
            {% endfor %}

            
        </main>

        {% include 'cart/cart_sidebar.html' %}
    </div>
</div>

{% endblock %}

menu/templates/menu/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/8a7b2ec054.js" crossorigin="anonymous"></script>
    <script>const STATIC_URL = "{% static 'menu/img/' %}";</script>
    <script src="{% static 'menu/js/sidebar.js' %}"></script>
    <script src="{% static 'menu/js/modal.js' %}"></script>
    <script src="{% static 'cart/js/sidebar-cart.js' %}"></script>
    <script src="{% static 'cart/js/main-cart-functions.js' %}"></script>
    <script src="{% static 'orders/js/confirm-order.js' %}"></script>

    {% block scripts %}
    {% endblock %}

    {% csrf_token %}

    <script>
        const REGISTER_URL = "{% url 'accounts:register' %}";
    </script>
    <script src="{% static 'menu/js/registration.js' %}"></script>

    <link rel="stylesheet" href="{% static 'menu/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>

    <template id="menuCartElement">
        {% include 'cart/menu_cart_element.html' %}
    </template>

    <template id="orderCartElement">
    {% include 'cart/order_cart_element.html' %}
    </template>
</head>
<body>

    {% include 'menu/header.html' %}

            {% block content %}
            {% endblock %}

    {% include 'menu/footer.html' %}

    {% include 'accounts/login_modal.html' %}
    {% include 'accounts/registration_modal.html' %}
    {% include 'menu/modal.html' %}
    {% include 'orders/confirm-order.html' %}


</body>
</html>

menu/templates/menu/modal.html
{% load static %}

<!-- Единое модальное окно -->
<div class="modal fade" id="productModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header modal-header-bg border-0 position-relative">
                <div class="d-flex align-items-center">
                    <h5 class="modal-title fw-bold me-3" id="productModalLabel"></h5>
                    <p class="modal-title mb-0">(<span id="modalProductCategory"></span>)</p>
                </div>
                <button type="button" class="btn-close position-absolute top-0 end-0 m-3" data-bs-dismiss="modal" aria-label="Закрыть"></button>
            </div>
            <div class="modal-body p-4">
                <div class="row">
                    <div class="col-md-6">
                        <div class="product-image-container">
                            <img id="modalProductImage" src="" class="img-fluid rounded-3" alt="">
                            <div class="product-badge" id="modalProductBadge"></div>
                        </div>
                        <div class="product-description mt-4">
                            <h5 class="fw-bold mb-3">Описание</h5>
                            <p id="modalProductDescription" class="text-muted"></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product-details">
                            <div class="price-container mb-4">
                                <h3 class="fw-bold mb-2" id="modalProductPrice"></h3>
                                <p class="text-muted mb-0" id="modalProductGrams"></p>
                            </div>

                            <div class="nutrition-section mb-4">
                                <div class="nutrition-info d-flex flex-column">
                                    <div class="nutrition-item d-flex align-items-center rounded-top-3">
                                        <div class="flex-grow-1 d-flex align-items-center">
                                            <div class="nutrition-icon mx-3"><i class="fas fa-fire"></i></div>
                                            <div class="nutrition-value" id="modalProductKalories"></div>
                                        </div>
                                        <div class="nutrition-label me-3">Калории</div>
                                    </div>
                                    <div class="nutrition-item d-flex align-items-center">
                                        <div class="flex-grow-1 d-flex align-items-center">
                                            <div class="nutrition-icon mx-3"><i class="fas fa-drumstick-bite"></i></div>
                                            <div class="nutrition-value" id="modalProductProtein"></div>
                                        </div>
                                            <div class="nutrition-label me-3">Белки</div>
                                    </div>
                                    <div class="nutrition-item d-flex align-items-center">
                                        <div class="flex-grow-1 d-flex align-items-center">
                                            <div class="nutrition-icon mx-3"><i class="fas fa-cheese"></i></div>
                                            <div class="nutrition-value" id="modalProductFat"></div>
                                        </div>
                                        <div class="nutrition-label me-3">Жиры</div>
                                    </div>
                                    <div class="nutrition-item d-flex align-items-center rounded-bottom-3">
                                        <div class="flex-grow-1 d-flex align-items-center">
                                            <div class="nutrition-icon mx-3"><i class="fas fa-bread-slice"></i></div>
                                            <div class="nutrition-value" id="modalProductCarbs"></div>
                                        </div>
                                        <div class="nutrition-label me-3">Углеводы</div>
                                    </div>
                                </div>
                            </div>

                            <div class="structure-section">
                                <h5 class="fw-bold mb-3">Состав</h5>
                                <p id="modalProductStructure" class="text-muted"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                    <i class="fas fa-times me-2"></i>Закрыть
                </button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" data-bs-toggle="addToCart" id="modalAddToCart">
                    <i class="fas fa-cart-plus me-2"></i>Добавить <span id="modalProductPriceBtn"></span>₽
                </button>
            </div>
        </div>
    </div>
</div>

menu/templates/menu/positions.html
{% load static %}

<section id="{{ category.name }}" class="category-section mb-5">
    <div class="section-header py-4">
        <h2 class="section-title">
            <i class="{{ category.icon_class }} me-3"></i>{{ category.name }}
        </h2>
    </div>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-3 row-cols-xxxl-4 row-cols-xxxxl-5 g-4">
        {% for product in category.products.all %}
            <div class="col">
                {% include 'menu/dish_card.html' %}
            </div>
        {% empty %}
            <div class="col-12">
                <div class="alert alert-info d-flex align-items-center">
                    <i class="fa-solid fa-info-circle me-2"></i>
                    <span>В этой категории пока нет блюд</span>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

menu/templates/menu/sidebar.html
<div id="categoriesSidebar" class="col-2 d-none d-xl-block sidebar ms-auto">
    <div class="position-sticky pt-2">
        <div class="sidebar-header">
            <h5 class="px-3">
                <i class="fa-solid fa-list me-2"></i>Категории
            </h5>
        </div>
        <ul class="nav flex-column" id="categories-nav">
            <li class="nav-item">
                <a class="nav-link category-link active" href="#novelty">
                    <i class="fas fa-star me-2"></i>Новинки
                    <span class="badge bg-primary">New</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link category-link" href="#hits">
                    <i class="fas fa-fire me-2"></i>Хиты продаж
                    <span class="badge bg-danger">Hot</span>
                </a>
            </li>

            {% for el in categories %}
            <li class="nav-item">
                <a class="nav-link category-link" href="#{{ el.name }}">
                    <i class="{{ el.icon_class }} me-2"></i>{{ el.name }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

menu/templates/menu/test.html
{% extends 'menu/layout.html' %}
{% load static %}

{% block title %}Тестовая страница{% endblock %}

{% block content %}



{% endblock %}